spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DocBucket_Development?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: sameera
      password: 1234
  application:
    name: DockBucket
server:
  port: 8081
